/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.masemoel.practica1_3_deint;

/**
 *
 * @author Masemo
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    
    public float primernumero;
    public float segundonumero;
    public String operador;
    
    public Calculadora(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        onebutton = new javax.swing.JButton();
        twobutton = new javax.swing.JButton();
        threebutton = new javax.swing.JButton();
        fourbutton = new javax.swing.JButton();
        fivebutton = new javax.swing.JButton();
        sixbutton = new javax.swing.JButton();
        sevenbutton = new javax.swing.JButton();
        eightbutton = new javax.swing.JButton();
        ninebutton = new javax.swing.JButton();
        plusbutton = new javax.swing.JButton();
        minusbutton = new javax.swing.JButton();
        mulbutton = new javax.swing.JButton();
        divbutton = new javax.swing.JButton();
        resbutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        calcultitle = new javax.swing.JLabel();
        decimalbutton = new javax.swing.JButton();
        zerobutton = new javax.swing.JButton();
        casilla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        onebutton.setText("1");
        onebutton.setMinimumSize(null);
        onebutton.setPreferredSize(null);
        onebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onebuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(onebutton, gridBagConstraints);

        twobutton.setText("2");
        twobutton.setMinimumSize(null);
        twobutton.setPreferredSize(null);
        twobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twobuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(twobutton, gridBagConstraints);

        threebutton.setText("3");
        threebutton.setMinimumSize(null);
        threebutton.setPreferredSize(null);
        threebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threebuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 10);
        getContentPane().add(threebutton, gridBagConstraints);

        fourbutton.setText("4");
        fourbutton.setMinimumSize(null);
        fourbutton.setPreferredSize(null);
        fourbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(fourbutton, gridBagConstraints);

        fivebutton.setText("5");
        fivebutton.setMinimumSize(null);
        fivebutton.setPreferredSize(null);
        fivebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivebuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(fivebutton, gridBagConstraints);

        sixbutton.setText("6");
        sixbutton.setMinimumSize(null);
        sixbutton.setPreferredSize(null);
        sixbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 10);
        getContentPane().add(sixbutton, gridBagConstraints);

        sevenbutton.setText("7");
        sevenbutton.setMinimumSize(null);
        sevenbutton.setPreferredSize(null);
        sevenbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(sevenbutton, gridBagConstraints);

        eightbutton.setText("8");
        eightbutton.setMinimumSize(null);
        eightbutton.setPreferredSize(null);
        eightbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(eightbutton, gridBagConstraints);

        ninebutton.setText("9");
        ninebutton.setMinimumSize(null);
        ninebutton.setPreferredSize(null);
        ninebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninebuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 10);
        getContentPane().add(ninebutton, gridBagConstraints);

        plusbutton.setText("+");
        plusbutton.setMinimumSize(null);
        plusbutton.setPreferredSize(null);
        plusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 11, 1, 1);
        getContentPane().add(plusbutton, gridBagConstraints);

        minusbutton.setText("-");
        minusbutton.setMinimumSize(null);
        minusbutton.setPreferredSize(null);
        minusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        getContentPane().add(minusbutton, gridBagConstraints);

        mulbutton.setText("x");
        mulbutton.setMinimumSize(null);
        mulbutton.setPreferredSize(null);
        mulbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 11, 1, 1);
        getContentPane().add(mulbutton, gridBagConstraints);

        divbutton.setText("/");
        divbutton.setMinimumSize(null);
        divbutton.setPreferredSize(null);
        divbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        getContentPane().add(divbutton, gridBagConstraints);

        resbutton.setText("=");
        resbutton.setMinimumSize(null);
        resbutton.setPreferredSize(null);
        resbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 11, 1, 1);
        getContentPane().add(resbutton, gridBagConstraints);

        clearbutton.setText("C");
        clearbutton.setMinimumSize(null);
        clearbutton.setPreferredSize(null);
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        getContentPane().add(clearbutton, gridBagConstraints);

        calcultitle.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        calcultitle.setText("CASIO");
        calcultitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 6;
        getContentPane().add(calcultitle, gridBagConstraints);

        decimalbutton.setText(".");
        decimalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalbuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 3);
        getContentPane().add(decimalbutton, gridBagConstraints);

        zerobutton.setText("0");
        zerobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerobuttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 3);
        getContentPane().add(zerobutton, gridBagConstraints);

        casilla.setBackground(new java.awt.Color(255, 255, 255));
        casilla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        casilla.setText("0");
        casilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        casilla.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(casilla, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zerobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerobuttonActionPerformed
        this.casilla.setText(this.casilla.getText()+"0");
    }//GEN-LAST:event_zerobuttonActionPerformed

    private void onebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onebuttonActionPerformed
        this.casilla.setText(this.casilla.getText()+"1");
    }//GEN-LAST:event_onebuttonActionPerformed

    private void twobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twobuttonActionPerformed
        this.casilla.setText(this.casilla.getText()+"2");
    }//GEN-LAST:event_twobuttonActionPerformed

    private void threebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threebuttonActionPerformed
        this.casilla.setText(this.casilla.getText()+"3");
    }//GEN-LAST:event_threebuttonActionPerformed

    private void fourbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourbuttonActionPerformed
        this.casilla.setText(this.casilla.getText()+"4");
    }//GEN-LAST:event_fourbuttonActionPerformed

    private void fivebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivebuttonActionPerformed
        this.casilla.setText(this.casilla.getText()+"5");
    }//GEN-LAST:event_fivebuttonActionPerformed

    private void sixbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixbuttonActionPerformed
        this.casilla.setText(this.casilla.getText()+"6");
    }//GEN-LAST:event_sixbuttonActionPerformed

    private void sevenbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenbuttonActionPerformed
        this.casilla.setText(this.casilla.getText()+"7");
    }//GEN-LAST:event_sevenbuttonActionPerformed

    private void eightbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightbuttonActionPerformed
        this.casilla.setText(this.casilla.getText()+"8");
    }//GEN-LAST:event_eightbuttonActionPerformed

    private void ninebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninebuttonActionPerformed
        this.casilla.setText(this.casilla.getText()+"9");
    }//GEN-LAST:event_ninebuttonActionPerformed

    private void decimalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalbuttonActionPerformed
        if(!(this.casilla.getText().contains("."))) {
            this.casilla.setText(this.casilla.getText()+".");
        }
    }//GEN-LAST:event_decimalbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        this.casilla.setText("0");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void plusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusbuttonActionPerformed
        this.primernumero = Float.parseFloat(this.casilla.getText());
        this.operador="+";
        this.casilla.setText("0");
    }//GEN-LAST:event_plusbuttonActionPerformed

    private void resbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resbuttonActionPerformed
        this.segundonumero = Float.parseFloat(this.casilla.getText());
        DialModal z = new DialModal(this, true);
        switch(this.operador){
            case "+":
                z.casillados.setText(Float.toString(primernumero+segundonumero));
                break;
            case "-":
                z.casillados.setText(Float.toString(primernumero-segundonumero));
                break;
            case "*":
                z.casillados.setText(Float.toString(primernumero*segundonumero));
                break;
            case "/":
                z.casillados.setText(Float.toString(primernumero/segundonumero));
                break;
        }
        z.setVisible(true);
    }//GEN-LAST:event_resbuttonActionPerformed

    private void minusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusbuttonActionPerformed
        this.primernumero = Float.parseFloat(this.casilla.getText());
        this.operador="-";
        this.casilla.setText("0");
    }//GEN-LAST:event_minusbuttonActionPerformed

    private void mulbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulbuttonActionPerformed
        this.primernumero = Float.parseFloat(this.casilla.getText());
        this.operador="*";
        this.casilla.setText("0");
    }//GEN-LAST:event_mulbuttonActionPerformed

    private void divbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divbuttonActionPerformed
        this.primernumero = Float.parseFloat(this.casilla.getText());
        this.operador="/";
        this.casilla.setText("0");
    }//GEN-LAST:event_divbuttonActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculadora dialog = new Calculadora(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calcultitle;
    private javax.swing.JLabel casilla;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton decimalbutton;
    private javax.swing.JButton divbutton;
    private javax.swing.JButton eightbutton;
    private javax.swing.JButton fivebutton;
    private javax.swing.JButton fourbutton;
    private javax.swing.JButton minusbutton;
    private javax.swing.JButton mulbutton;
    private javax.swing.JButton ninebutton;
    private javax.swing.JButton onebutton;
    private javax.swing.JButton plusbutton;
    private javax.swing.JButton resbutton;
    private javax.swing.JButton sevenbutton;
    private javax.swing.JButton sixbutton;
    private javax.swing.JButton threebutton;
    private javax.swing.JButton twobutton;
    private javax.swing.JButton zerobutton;
    // End of variables declaration//GEN-END:variables
}
