/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.masemoel.practica1_4;

import java.awt.Color;
import javax.swing.JFileChooser;

/**
 *
 * @author Masemo
 */
public class Ventana1 extends javax.swing.JFrame {
    boolean activadosbotones = true;
    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interfazgroup = new javax.swing.ButtonGroup();
        panelprincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        selecbutton = new javax.swing.JButton();
        seleccionfield = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        useraddition = new javax.swing.JTextField();
        addtextbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usertext = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        modalbutton = new javax.swing.JButton();
        nomodalbutton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        clarobutton = new javax.swing.JRadioButtonMenuItem();
        oscurobutton = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        botonescheck = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelprincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setOpaque(false);

        jPanel3.setOpaque(false);

        selecbutton.setText("Abrir selector");
        selecbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecbuttonActionPerformed(evt);
            }
        });

        seleccionfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(seleccionfield, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(selecbutton)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(selecbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Archivo", jPanel3);

        jPanel4.setOpaque(false);

        useraddition.setToolTipText("");
        useraddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useradditionActionPerformed(evt);
            }
        });

        addtextbutton.setText("Añadir");
        addtextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtextbuttonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(usertext);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(useraddition, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addtextbutton)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useraddition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addtextbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Lista", jPanel4);

        jPanel2.setOpaque(false);

        modalbutton.setText("Modal");
        modalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modalbuttonActionPerformed(evt);
            }
        });

        nomodalbutton.setText("No modal");
        nomodalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomodalbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(modalbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomodalbutton)
                .addGap(121, 121, 121))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modalbutton)
                    .addComponent(nomodalbutton))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Diálogos", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout panelprincipalLayout = new javax.swing.GroupLayout(panelprincipal);
        panelprincipal.setLayout(panelprincipalLayout);
        panelprincipalLayout.setHorizontalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelprincipalLayout.setVerticalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Interfaz");

        interfazgroup.add(clarobutton);
        clarobutton.setSelected(true);
        clarobutton.setText("Modo claro");
        clarobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clarobuttonActionPerformed(evt);
            }
        });
        jMenu1.add(clarobutton);

        interfazgroup.add(oscurobutton);
        oscurobutton.setText("Modo oscuro");
        oscurobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oscurobuttonActionPerformed(evt);
            }
        });
        jMenu1.add(oscurobutton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Botones");

        botonescheck.setSelected(true);
        botonescheck.setText("Habilitar edición");
        botonescheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonescheckActionPerformed(evt);
            }
        });
        jMenu2.add(botonescheck);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonescheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonescheckActionPerformed
        if (activadosbotones) {
            modalbutton.setEnabled(false);
            nomodalbutton.setEnabled(false);
            selecbutton.setEnabled(false);
            seleccionfield.setEnabled(false);
            addtextbutton.setEnabled(false);
            usertext.setEnabled(false);
            useraddition.setEnabled(false);
            activadosbotones = false;
        } else {
            modalbutton.setEnabled(true);
            nomodalbutton.setEnabled(true);
            selecbutton.setEnabled(true);
            seleccionfield.setEnabled(true);
            addtextbutton.setEnabled(true);
            usertext.setEnabled(true);
            useraddition.setEnabled(true);
            activadosbotones = true;
        }
    }//GEN-LAST:event_botonescheckActionPerformed

    private void clarobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clarobuttonActionPerformed
        panelprincipal.setBackground(Color.white);
        seleccionfield.setBackground(Color.white);
        seleccionfield.setForeground(Color.black);
        useraddition.setBackground(Color.white);
        useraddition.setForeground(Color.black);
        usertext.setBackground(Color.white);
        usertext.setForeground(Color.black);
    }//GEN-LAST:event_clarobuttonActionPerformed

    private void oscurobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oscurobuttonActionPerformed
        panelprincipal.setBackground(Color.DARK_GRAY);
        seleccionfield.setBackground(Color.DARK_GRAY);
        seleccionfield.setForeground(Color.white);
        useraddition.setBackground(Color.DARK_GRAY);
        useraddition.setForeground(Color.white);
        usertext.setBackground(Color.DARK_GRAY);
        usertext.setForeground(Color.white);
    }//GEN-LAST:event_oscurobuttonActionPerformed

    private void modalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modalbuttonActionPerformed
        ModalDialog mod = new ModalDialog(this, true);
        mod.setVisible(true);
    }//GEN-LAST:event_modalbuttonActionPerformed

    private void nomodalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomodalbuttonActionPerformed
        NoModalDialog nomod = new NoModalDialog(this, true);
        nomod.setVisible(true);
    }//GEN-LAST:event_nomodalbuttonActionPerformed

    private void selecbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecbuttonActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(fc);
        seleccionfield.setText(fc.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_selecbuttonActionPerformed

    private void addtextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtextbuttonActionPerformed
        usertext.setText(usertext.getText()+useraddition.getText()+"\n");
    }//GEN-LAST:event_addtextbuttonActionPerformed

    private void useradditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useradditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useradditionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtextbutton;
    private javax.swing.JCheckBoxMenuItem botonescheck;
    private javax.swing.JRadioButtonMenuItem clarobutton;
    private javax.swing.ButtonGroup interfazgroup;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton modalbutton;
    private javax.swing.JButton nomodalbutton;
    private javax.swing.JRadioButtonMenuItem oscurobutton;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JButton selecbutton;
    private javax.swing.JTextField seleccionfield;
    private javax.swing.JTextField useraddition;
    private javax.swing.JTextPane usertext;
    // End of variables declaration//GEN-END:variables
}
